### ISSUE TITLE
Downloaded video Are not supported in WhatsApp

### ISSUE THREAD

**Issue by Pritam34** [JunkFood02/Seal#959] opened 2023-07-25 04:50 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I download video from youtube and go to put that video in whatsapp status, that video is not supported by whatsapp.
![Screenshot_2023-07-25-10-14-57-807_com whatsapp](https://github.com/JunkFood02/Seal/assets/77155608/dfdd772a-a352-4d06-84b1-163a4eea5fd8)

### Error reports

Downloaded video Are not support in WhatsApp.

### Screenshots & Screen Records

![Screenshot_2023-07-25-10-14-57-807_com whatsapp](https://github.com/JunkFood02/Seal/assets/77155608/5976f45d-4534-402d-acc9-21bee80ac07b)
![Screenshot_2023-07-25-10-14-50-483_com whatsapp](https://github.com/JunkFood02/Seal/assets/77155608/41b979d4-9ea4-4eca-b5a6-280b7d78ebd2)

### Device info

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

### Additional context

Please solve this problem. Otherwise I have to uninstall your seal app.

**Comment by JunkFood02** [comment] 2023-07-25 05:58
Duplicate of #889

**Closed by JunkFood02** 2023-07-25 05:58 UTC
Labels: bug
