### ISSUE TITLE
Unable to download reel from instagram

### ISSUE THREAD

**Issue by maulikherma** [JunkFood02/Seal#737] opened 2023-05-01 18:35 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Unable to download a reel video from instagram

### Error reports

URL: https://www.instagram.com/reel/CpKoOXTApHX/?igshid=MDJmNzVkMjY=
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CpKoOXTApHX: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230501-235943_Seal](https://user-images.githubusercontent.com/131992634/235507608-019ad577-f846-459b-8e26-7f6ecfe0c5ad.jpg)

### Device info

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by JunkFood02** [comment] 2023-05-01 19:05
duplicate of #733

**Closed by JunkFood02** 2023-05-01 19:05 UTC
Labels: bug
