### ISSUE TITLE
[Feature Request] Display Yt-dlp warnings within the log

### ISSUE THREAD

**Issue by powerfulsaber** [JunkFood02/Seal#696] opened 2023-04-07 11:13 UTC
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Seal doesn't display warnings yt-dlp would output when downloading a video.

### Describe the solution you'd like

Seal should at least output warnings yt-dlp would inside the logs. Having it appear as a notification would be great too.

### Additional context

I noticed this due to a bug in yt-dlp, where for some videos on TikTok, their feed isn't able to be downloaded. This results in certain strings not able to be retrieved, like "creator", and replaces them with  "NA" instead. I didn't notice anything off in the logs Seal provided, so I was struggling to find the issue. But then I tested this on my PC, and it displayed a warning which helped locate the open issue on yt-dlp's repository. If Seal could start displaying warnings, it would help a lot.

**Comment by JunkFood02** [comment] 2023-04-07 15:15
Use custom commands

**Comment by JunkFood02** [comment] 2023-04-10 17:57
😢 Probably a duplicate of #180 and #254

**Closed** 2023-04-11 08:10 UTC
Labels: bug
