### ISSUE TITLE
I can't download audios

### ISSUE THREAD

**Issue by Leoncito123** [JunkFood02/Seal#1486] opened 2024-05-03 02:09 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I can't download audios from YouTube, I'm missing libraries according to the error

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2024.04.09

URL: https://youtube.com/watch?v=nA0fXQDKyho&si=gJ38a7D4Ejnv2cVV
CANNOT LINK EXECUTABLE "/data/app/~~JTGfVzucYNKjEktdAcO-0Q==/com.junkfood.seal-nCbPHC4NfQ2UKMtu-N9JRQ==/lib/arm64/libpython.so": library "libandroid-support.so" not found: needed by main executable

**Comment by JunkFood02** [comment] 2024-05-03 17:15
Can you try https://github.com/JunkFood02/Seal/releases/tag/v2.0.0-alpha.1?

**Comment by JunkFood02** [comment] 2024-05-03 17:15
Duplicate of #1404

**Closed by JunkFood02** 2024-05-03 17:15 UTC
Labels: bug, new issue

**Comment by Leoncito123** [comment] 2024-05-03 17:47
Yes, I can download now, thanks 

> Can you try https://github.com/JunkFood02/Seal/releases/tag/v2.0.0-alpha.1?
