### ISSUE TITLE
Unable to download video

### ISSUE THREAD

**Issue by ericsomto** [JunkFood02/Seal#636] opened 2023-02-23 03:49 UTC
App version: 1.8.2-(F-Droid) (10823)
Device information: Android 9 (API 28)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2022.11.11

URL: https://youtu.be/RuqtTEeGF5k
ERROR: [youtube] RuqtTEeGF5k: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by JunkFood02** [comment] 2023-02-23 06:53
Duplicate of #600

**Closed by JunkFood02** 2023-02-23 06:53 UTC

**Comment by ericsomto** [comment] 2023-02-24 03:43
I got to fix the app by updating yt dlp
