### ISSUE TITLE
 Could not fetch video info

### ISSUE THREAD

**Issue by MingMing0000** [JunkFood02/Seal#1579] opened 2024-07-14 10:27 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.12.1 (11212)
Device information: Android 5.1 (API 22)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.09

URL: https://www.youtube.com/watch?v=ny75CR4lhTo
WARNING: linker: libcrypto.so.1.1: unused DT entry: type 0x6ffffef5 arg 0x88a0
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
WARNING: linker: libcrypto.so.1.1: unused DT entry: type 0x6ffffffe arg 0x44560
WARNING: linker: libcrypto.so.1.1: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libssl.so.1.1: unused DT entry: type 0x6ffffef5 arg 0x18b0
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
WARNING: linker: libssl.so.1.1: unused DT entry: type 0x6ffffffe arg 0xd388
WARNING: linker: libssl.so.1.1: unused DT entry: type 0x6fffffff arg 0x2
Traceback (most recent call last):
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/subprocess.py", line 64, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 16, in <module>
  File "/data/data/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/subprocess.py", line 69, in <module>
    import _posixsubprocess
ImportError: dlopen failed: library name "/data/data/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38.so" too long

### Screenshots & Screen Records

![Screenshot_2024-07-14-18-26-34](https://github.com/user-attachments/assets/1219d59f-8130-4822-accf-db78b86e2a7d)

**Comment by JunkFood02** [comment] 2024-08-14 13:38
This doesn't look normal, did you try disabling cookies?

**Comment by Muslimman-1** [comment] 2024-08-17 09:13
> This doesn't look normal, did you try disabling cookies?

it happens with me as well
cannot download playlists due to this error

I'm trying and I'm sure all options are correct

**Comment by JunkFood02** [comment] 2024-08-18 06:48
Duplicate of #1096

**Closed by JunkFood02** 2024-08-18 06:48 UTC
Labels: bug, question

**Comment by Muslimman-1** [comment] 2024-08-18 08:13
it's updated to the last version
