### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Darkion47** [JunkFood02/Seal#643] opened 2023-02-26 06:48 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Couldn't download anything. Its shows the following error messages.

### Error reports

App version: 1.7.3-(F-Droid) (10734)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://youtu.be/ZlOPcKmOTog
ERROR: [youtube] ZlOPcKmOTog: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230226-124453](https://user-images.githubusercontent.com/94956151/221396375-2a795886-407d-4b80-93ae-d90ac44ec894.png)

**Comment by JunkFood02** [comment] 2023-02-26 07:21
Duplicate of #600

**Closed** 2023-02-26 07:21 UTC
Labels: bug
