### ISSUE TITLE
App version: 1.8.2-(F-Droid) (10824) Device information: Android 10 (API 29) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: null  URL: https://youtu.be/7g1LcRZtQm4 ERROR: [youtube] 7g1LcRZtQm4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[Bug Report]

### ISSUE THREAD

**Issue by swati488** [JunkFood02/Seal#615] opened 2023-02-19 04:52 UTC
### Describe the bug

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtu.be/7g1LcRZtQm4
ERROR: [youtube] 7g1LcRZtQm4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by JunkFood02** [comment] 2023-02-19 06:15
Duplicate of #599

**Closed by JunkFood02** 2023-02-19 06:15 UTC
Labels: bug
