### ISSUE TITLE
Background download

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#78] opened 2022-07-30 21:45 UTC
Downloading in background is slower than downloading in foreground.
For Reference|
● foreground & background:  https://drive.google.com/drive/folders/1rdypbBXqnkPmO-D2Q3KX6ijlV80ouhKl

**Comment by JunkFood02** [comment] 2022-07-31 05:09
It seems like restrictions from the OS, and we can't do anything about it. The OS will always limit the resources that applications in the background state can use, or even force closing them. 
Currently, Seal is using a workaround for downloading in the background, you can find some discussions in #31 and #38.

**Comment by Marco-9456** [comment] 2022-07-31 05:17
> It seems like restrictions from the OS, and we can't do anything about it. The OS will always limit the resources that applications in the background state can use, or even force closing them. Currently, Seal is using a workaround for downloading in the background, you can find some discussions in #31 and #38.

I understand, thanks for clarifying. I thought it was an app related issue

**Comment by senolfndk** [comment] 2022-07-31 11:30
mp3 and video download speed is very slow

**Comment by JunkFood02** [comment] 2022-07-31 11:40
> mp3 and video download speed is very slow

@senolfndk 
[dvd](https://github.com/yausername/dvd) uses the same library to download a video. You can try it out and test if the problem is on our side. Also, please provide more detailed information in a new issue.

**Closed by JunkFood02** 2022-07-31 11:40 UTC
