### ISSUE TITLE
[Feature Request] Option to append Custom Command - Template to default/auto-generated command.

### ISSUE THREAD

**Issue by RohitSurwase** [JunkFood02/Seal#741] opened 2023-05-06 07:40 UTC
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Custom Command-
There should be an option to append Custom Command - Template instead of just using that command.

I like the default/auto-generate command used by the App but sometime I would like to customize it further. For example adding filter to the play-list videos using `--match-filter`.

Currently, we can either use custom command or the auto-generate command by the App.

### Describe the solution you'd like

Give an option to append Custom Command - Template to the existing/auto-generated command.

**Comment by JunkFood02** [comment] 2023-05-06 13:17
duplicate of #357

**Closed by JunkFood02** 2023-05-06 13:17 UTC
Labels: enhancement
