### ISSUE TITLE
[Feature Request] I really hope that in the future we have the ability to rename files before downloading them. It would be so much more convenient to be able to give a file a specific name before downloading it, rather than having to rename it after the fact. I think it would be a great feature, and I'm sure many people would find it very useful

### ISSUE THREAD

**Issue by Al-1A** [JunkFood02/Seal#465] opened 2022-12-29 23:11 UTC
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by JunkFood02** [comment] 2022-12-30 06:22
Duplicate of #234

**Closed by JunkFood02** 2022-12-30 06:22 UTC
Labels: enhancement
