### ISSUE TITLE
original file name of VIDEOS

### ISSUE THREAD

**Issue by amir385276** [JunkFood02/Seal#722] opened 2023-04-24 15:49 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

how to remove any characters in the end of filename of youtube videos - 
it's 11 character and save after downloading a video from youtube
i know there is a solution way in the youtube-dl and ytdl-p

thanks

### Error reports

filename

### Device info

App Version: 1.9.1

**Comment by JunkFood02** [comment] 2023-04-27 07:44
Duplicate of #675

**Closed by JunkFood02** 2023-04-27 07:44 UTC
Labels: bug
