### ISSUE TITLE
Override fields

### ISSUE THREAD

**Issue by yant0** [JunkFood02/Seal#95] opened 2022-08-03 11:47 UTC
I used seal to download album/playlist from soundcloud it seperates each tracks to their own albums. I would like that fixed or maybe add the option to override fields. I used `--parse-metadata` in dvd before, but its for giving tracks their own track number (seal doesnt number the tracks with the native downloader). I think that command can be used in this case too. Either way this is a great feature to have.

**Comment by JunkFood02** [comment] 2022-08-03 12:09
Mark the album of the audio file with the title is the [intended behavior](https://github.com/JunkFood02/Seal/blob/main/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L112) when no album information is provided from the website. I'll look into it.

**Comment by yant0** [comment] 2022-08-03 12:36
I originally wanted the feature to number tracks but i tested the app to download playlost from soundcloud it ended up splitting each one.

I wanted to have a prefference to set specific fields manually if some fields i deem to be weird. The function will be just like the custom commands but its set up in the settings and only effects --parse-metadata

honestly, after taking a dump i realize how cumbersome this request is. Feel free to drop this or have a better idea implemented of this

**Comment by yant0** [comment] 2022-08-03 12:39
[This](https://github.com/yausername/dvd/issues/33) might be a better idea

**Comment by JunkFood02** [comment] 2022-08-03 13:57
> I originally wanted the feature to number tracks but i tested the app to download playlist from soundcloud it ended up splitting each one.
> 
> I wanted to have a preference to set specific fields manually if some fields i deem to be weird. The function will be just like the custom commands but its set up in the settings and only effects --parse-metadata
> 
> honestly, after taking a dump i realize how cumbersome this request is. Feel free to drop this or have a better idea implemented of this

Could you please provide a link to the playlist for testing?

**Comment by yant0** [comment] 2022-08-03 16:10
https://m.soundcloud.com/ariaveil/sets/newbliss

**Comment by Marco-9456** [comment] 2022-08-03 16:13
> [This](https://github.com/yausername/dvd/issues/33) might be a better idea

Yeah this is better

**Comment by JunkFood02** [comment] 2022-08-03 17:53
I see. This seems like a site-specified problem and can maybe be fixed by a workaround.

**Comment by JunkFood02** [comment] 2022-08-03 18:59
![Screenshot_20220804-025919](https://user-images.githubusercontent.com/69683722/182688019-30565a9d-055d-49a0-b619-d3c357038c0e.png)
🧐

**Comment by yant0** [comment] 2022-08-04 04:56
I would suggest not to hard code the track numbers into native download option. In soundcloud, we can download whole discog and in my preference i would have the track numbers to be 0 since there could be new releases.

**Comment by JunkFood02** [comment] 2022-08-04 05:37
> I would suggest not to hard code the track numbers into native download option. In soundcloud, we can download whole discog and in my preference i would have the track numbers to be 0 since there could be new releases.

I thought it would be natural to specify the track number by its position in the playlist(album).

**Comment by yant0** [comment] 2022-08-04 09:53
> > I would suggest not to hard code the track numbers into native download option. In soundcloud, we can download whole discog and in my preference i would have the track numbers to be 0 since there could be new releases.
> 
> I thought it would be natural to specify the track number by its position in the playlist(album).

I put artists singles into one folder. So when i batch download a artist i would like to put their singles there in the singles folder without the track numbers being mixed up.

Thats just my use case. Im fine with it being hard coded but i need to retag each one of them and put it in the folder.

**Comment by JunkFood02** [comment] 2022-08-04 12:33
A folder is where to place the audio files. The album, artist, title, and album cover are metadata embedded into an audio file. They're not respective with where the files are placed. The problem with SoundCloud is that they use a playlist as an album and do not provide album metadata. So the fix is to use the playlist title to tag songs from the same album(playlist). Besides the album title and the track number, the other metadata extracted from SoundCloud seems fine.

**Closed** 2022-08-05 09:29 UTC
Labels: enhancement

**Comment by JunkFood02** [comment] 2022-08-11 05:18
> [This](https://github.com/yausername/dvd/issues/33) might be a better idea

Implemented in v1.0.3
