### ISSUE TITLE
Unable to extract uploader ID Error

### ISSUE THREAD

**Issue by Natekmbowie** [JunkFood02/Seal#630] opened 2023-02-21 06:23 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

As of recently each time I go to download a YouTube video I get an issue like this. I'm on the latest FDroid version of the app on a Pixel 5 running GrapheneOS; however, I had previously shared the app so I had several people asked me about the issue leading me to assume it is pretty universal.

I was able to successfully try to download a video from Rumble, which leads me to believe their is a chance this issue may be upstream with a YT change that effected the version YT-DL implemented in the app; but that sort of investigation is far above my expertise.

### To Reproduce

1. Download the latest version from FDroid
2. Attempt to download a video from YouTube

### Error reports

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: 
ERROR: [youtube] QQTERGmtNKA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![IMG_20230221_011003](https://user-images.githubusercontent.com/115597867/220263476-36fc6ccf-9a71-41ec-a057-4a56552bbdf9.jpg)

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by JunkFood02** [comment] 2023-02-21 08:48
Duplicate of #600

**Closed by JunkFood02** 2023-02-21 08:48 UTC
Labels: bug
