### ISSUE TITLE
[Feature Request]   ability to change file name before download.

### ISSUE THREAD

**Issue by soymadip** [JunkFood02/Seal#580] opened 2023-02-06 06:26 UTC
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

As for now we can't change the name before downloading any video. 
If we are downloading any video with different resolution, seal overwrites the previous video. 
And also we can't change the name if we wanna save the video with custom name.

### Describe the solution you'd like

Like [PowerTube](https://github.com/razar-dev/PowerTube)/Snaptube, tapping in the title should popup a box from where we can change the title of the video. 

https://user-images.githubusercontent.com/84225810/216896841-c2b12d34-6fac-422f-a4ee-3ee7199f4ad6.mp4

### Video link

All the videos will be beneficial

**Comment by JunkFood02** [comment] 2023-02-06 06:54
duplicate of #234

**Closed by JunkFood02** 2023-02-06 06:54 UTC
Labels: enhancement
