### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by Puarasan** [JunkFood02/Seal#1000] opened 2023-08-21 10:53 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

![Screenshot_20230821_162049_Seal](https://github.com/JunkFood02/Seal/assets/105143579/523eca1e-f451-4102-bc56-ebd278f64d56)
![Screenshot_20230821_162058_Seal](https://github.com/JunkFood02/Seal/assets/105143579/2ad92dc9-0790-4baf-a774-bb7493f9a0d2)

### Error reports

![Screenshot_20230821_161749_WhatsApp](https://github.com/JunkFood02/Seal/assets/105143579/a4bbbfd6-1ae4-4b2c-8046-2c5758d6632f)

### Screenshots & Screen Records

![Screenshot_20230821_161749_WhatsApp](https://github.com/JunkFood02/Seal/assets/105143579/1177c1b0-9122-4267-99ac-3b26d210b069)
![Screenshot_20230821_162049_Seal](https://github.com/JunkFood02/Seal/assets/105143579/bd283843-3b72-46af-be50-fd9df7cb5014)
![Screenshot_20230821_162058_Seal](https://github.com/JunkFood02/Seal/assets/105143579/4bf00d62-496c-4d90-8e8a-5ccf79dbb8bc)

### Device info

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

### Additional context

I'm using seal
It's very useful but some format not working on whatsapp and other social media sites

**Comment by JunkFood02** [comment] 2023-08-21 17:47
Duplicate of #889

**Closed by JunkFood02** 2023-08-21 17:47 UTC
Labels: bug
