### ISSUE TITLE
Some songs from my youtube music playlist won't get downloaded

### ISSUE THREAD

**Issue by SuperPou1** [JunkFood02/Seal#864] opened 2023-06-08 20:47 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I was trying to download a playlist i made with youtube music, which has 65 songs. When I put in the link of that playlist into seal, it only saw 60 songs, some were missing. 

### To Reproduce

1. Copy the link from my playlist from the yputube music app using the share feature
2. Put in link to seal with default settings
3. See that there are only 60 songs to be selected, even though my playlist had 65

### Error reports

60 songs to be selected instead of 65

### Device info

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by Marco-9456** [comment] 2023-06-08 21:15
This is not a bug, the 5 Songs that weren't selected are probably removed, unavailable or hidden by the uploader, that's why you couldn't download them.

**Comment by SuperPou1** [comment] 2023-06-09 07:50
> This is not a bug, the 5 Songs that weren't selected are probably removed, unavailable or hidden by the uploader, that's why you couldn't download them.

Are you sure? I can download these songs seperately

**Comment by JunkFood02** [comment] 2023-06-09 07:57
Please provide the link to the playlist or we can't locate where the issue is

**Comment by SuperPou1** [comment] 2023-06-09 08:03
[here](https://music.youtube.com/playlist?list=PLPZMHnIh7KewVMjBe_gEuFr3DMp2VS7iX&feature=share)

**Comment by SuperPou1** [comment] 2023-06-09 08:16
BTW, some if the songs that were missing are "I swallowed shampoo" and "running up that hill"

**Comment by JunkFood02** [comment] 2023-06-23 19:47
fixed in v1.10.0-beta.3

**Closed** 2023-06-24 11:09 UTC
Labels: bug, pending
