### ISSUE TITLE
Tiktok video not downloading, plus watermark 

### ISSUE THREAD

**Issue by flame1207** [JunkFood02/Seal#1487] opened 2024-05-03 10:48 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Tiktok link is not working 
Error pops up
The only options is a download with the watermark 

### Error reports

App version: 1.12.1 (11210)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.28.232723

URL: https://vm.tiktok.com/ZMMG8xsVW/
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 3)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 3)
WARNING: [TikTok] 7361974749993487647: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
ERROR: [TikTok] 7361974749993487647: Requested format is not available. Use --list-formats for a list of available formats

**Comment by JunkFood02** [comment] 2024-05-03 17:17
Duplicate of #1376

**Closed by JunkFood02** 2024-05-03 17:17 UTC
Labels: bug, new issue

**Comment by Ismail00008** [comment] 2024-05-05 20:56
I've had the same problem and when the download is available the quality is terrible.ive reported the issue and its been closed twice but nothings changed
