### ISSUE TITLE
ReVanced Overlay UI bug

### ISSUE THREAD

**Issue by H4zh4n** [JunkFood02/Seal#1526] opened 2024-06-09 11:46 UTC
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm Using ReVanced, with Seal's package set for the External Download button.
When a video is playing and I click the download button, it turns the playing video into a floating one and displays Seal's (Configure before download).

However, if I tap `Share` on the video > then Seal `quick download` this doesn't happen. Meaning it doesn't turn the video into a floating one, rather just displays the download configuration above the video.

### Describe the solution you'd like

I was wondering if there was a way to make the download button be same as the sharing option and not have it turn the video into floating (Best of both worlds). It is a bit cumbersome that it turns into floating with download button, and you'll have to get back to it two taps later. And also tedious through the share option if I don't want it to turn into floating, Have to share then find Seal... etc.

### Undesired effect through Download button
https://github.com/JunkFood02/Seal/assets/47919702/4c900d74-a544-4145-967a-7d692cec7955

### Desired (but wanted with Download button not share)
https://github.com/JunkFood02/Seal/assets/47919702/2beb5fc1-0769-45b3-b08b-5a4e524f51ed

### Additional context

- The phone I'm using is Xiaomi POCO X6 Pro. Android 14, OxygenOS.

- Didn't do anything special for this to occur. Just set `Downloader package name` to `com.junkfood.seal` in Revanced. And made sure `Configure before download` is enabled in Seal.
- I Have `Open new windows while running` granted In Other permissions for Seal.

**Comment by JunkFood02** [comment] 2024-06-15 07:58
Duplicate of #506

**Closed by JunkFood02** 2024-06-15 07:58 UTC
Labels: enhancement, new issue
