### ISSUE TITLE
Download video on YouTube [Bug Report]

### ISSUE THREAD

**Issue by shycat28** [JunkFood02/Seal#609] opened 2023-02-18 06:10 UTC
### Describe the bug

Unable to download video on YouTube... Was working before 🤷

### To Reproduce

You can rather share with Seal or copy/paste link
It will not work...

### Error reports & Screenshots

URL: https://youtu.be/9O4_awEHh1g
ERROR: [youtube] 9O4_awEHh1g: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.7.3-(F-Droid) (10733)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by JunkFood02** [comment] 2023-02-18 06:35
Duplicate of #599

**Closed by JunkFood02** 2023-02-18 06:35 UTC
Labels: bug
