### ISSUE TITLE
Error download from youtube

### ISSUE THREAD

**Issue by KhaledKhaled0909** [JunkFood02/Seal#635] opened 2023-02-22 15:16 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Error when downloading audio from youtube

### To Reproduce

Share a video from youtube

### Error reports

App version: 1.8.0-(F-Droid) (10804)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2022.10.04

URL: https://youtu.be/n3ub8zgYKHA
ERROR: [youtube] n3ub8zgYKHA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230222-170922_Seal](https://user-images.githubusercontent.com/117318181/220663846-7e9500e5-b034-4493-89d0-12c00f14d4ff.png)

### Device info

Share a video from youtube that does not allow me do download on youtube app.

### Additional context

None

**Comment by JunkFood02** [comment] 2023-02-22 15:27
duplicate of #600

**Closed by JunkFood02** 2023-02-22 15:27 UTC
Labels: bug
