### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by DarkFuryYT** [JunkFood02/Seal#616] opened 2023-02-19 06:21 UTC
### Describe the bug

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtube.com/shorts/WhE79mkCdM8?feature=share
ERROR: [youtube] WhE79mkCdM8: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

ERROR: [generic] 'App version: 1.8.2-(F-Droid) (10824)\nDevice information: Android 12 (API 31)\nSupported ABIs: [arm64-v8a, armeabi-v7a, armeabi]\nYt-dlp version: null\n\nURL: https://youtube.com/shorts/WhE79mkCdM8?feature=share\nERROR: [youtube] WhE79mkCdM8: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtube.com/shorts/WhE79mkCdM8?feature=share
ERROR: [youtube] WhE79mkCdM8: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U" ) to search YouTube

### To Reproduce

1. Paste link in download the box
2. Click download icon

### Error reports & Screenshots

![Screenshot_20230219-114959_Seal](https://user-images.githubusercontent.com/125786378/219932478-33301de9-07e5-446d-8746-6b2a58957365.jpg)

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

### Additional context

Na

**Comment by JunkFood02** [comment] 2023-02-19 06:38
Duplicate of #599

**Closed by JunkFood02** 2023-02-19 06:38 UTC
Labels: bug
