### ISSUE TITLE
.mkv instead of .mp4

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#238] opened 2022-09-17 22:49 UTC
### Describe the bug

I set it to mp4 by default, but it saves in mkv

This always happens. Even if I press manually

### To Reproduce

Download the video and check

### Device info

App version: 1.3.1 (10310)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2263 x 1078

**Comment by JunkFood02** [comment] 2022-09-19 08:37
Try v1.3.2

**Comment by JunkFood02** [comment] 2022-09-19 10:43
Please provide the link to the video, or I'd close this due to insufficient information

**Comment by Marco-9456** [comment] 2022-09-19 20:12
> > Please provide the link to the video, or I'd close this due to insufficient information
> 
> It's for all the videos. I will record a confirmation video
> 
> I don't know what information to give you

Reproduce the bug and make a screen record,

Also are you using `Embed subtitles` option if so then this is a normal behavior that Seal does to avoid issues that appears if the subtitles format is `".ass"`

**Comment by Marco-9456** [comment] 2022-09-19 20:26
> > Please provide the link to the video, or I'd close this due to insufficient information
> 
> It's for all the videos. I will record a confirmation video
> 
> I don't know what information to give you

If this is what you're doing then this isn't a Bug

<details markdown='1'><summary> Show Screen record </summary>

https://user-images.githubusercontent.com/41828058/191109563-b2ca990d-d3b6-42ff-9853-6d6e02cad21a.mp4

</details>

**Comment by JunkFood02** [comment] 2022-09-20 00:20
The video just indicated you enabled the "embed subtitle" option. Simply copying and pasting your video link here is just fine and you're providing nothing which can help solve your problem. Closing this for not wanna have my time wasted 😌👌

**Closed by JunkFood02** 2022-09-20 00:20 UTC
Labels: bug

**Comment by JunkFood02** [comment] 2022-09-20 03:56
![Screenshot_20220920-115548-408](https://user-images.githubusercontent.com/69683722/191164102-f3db51a8-15c7-4418-b6ce-d0fad1ab711d.png)

**Comment by JunkFood02** [comment] 2022-09-20 03:58
> HOWEVER, the average user, is supposed to tell you useful information? All I see is that it didn't save in mp4. You think I'm a developer? No! You write it like I'm stupid. But I'm not. You asked for a recording (proof of error). I sent it to you. There's nothing more I can do! You are a developer. You look for a bug in the code, not me.

The "average" user won't be yelling at the developer for a "bug" which is cannot be reproduced I think 😉

**Comment by BobbyESP** [comment] 2022-09-20 05:06
We just wanted you to give us the link of the video that you wanted to download. We dont care if it's an NFSW video, a video for kids or whatever, the only thing that we want is to improve the app, so please, be respectful .

By the way, the app correctly converts the videos to .mp4

Video without subtitles activated: https://user-images.githubusercontent.com/60316747/191171938-752261eb-bb0e-45c4-bfae-0550e6fa6562.mp4

Video with subtitles activated:
https://user-images.githubusercontent.com/60316747/191172043-14eb7641-3544-4c9e-ab32-c660299f7e92.mp4

**Comment by Marco-9456** [comment] 2022-09-20 19:00
> I don't understand why you need the link if this happens with all videos.

Because he needs to reproduce the "bug"
If it's not reproducible then he can't fix it

**Comment by JunkFood02** [comment] 2022-09-21 03:44
> if this happens with all videos.

No it doesn't. 🤣 Just wondering when are you willing to share your little secret video link with us instead of  yelling hysterically.
