### ISSUE TITLE
convert .vtt to .srt

### ISSUE THREAD

**Issue by amir385276** [JunkFood02/Seal#708] opened 2023-04-14 13:43 UTC
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Hi guys
i try some commands to convert the .vtt subtitle from youtube videos to .srt, but i can't do it.

please create or help to convert all .vtt to .srt

thanks

**Comment by Marco-9456** [comment] 2023-04-14 19:06
Add this to your Custom Command:

`--convert-subs srt`

**Comment by amir385276** [comment] 2023-04-15 12:36
Hello Marco-9456
I try this command and working fine 
thanks

but when i download a video from youtube - but after the download i watch the green cheese cubes
i don't know why do it that - specially in the some of video have a big time and size
![Uploading Screenshot_۲۰۲۳-۰۴-۱۵-۱۳-۳۴-۲۴-۶۹۵_org.videolan.vlc.jpg…]()

![Uploading Screenshot_۲۰۲۳-۰۴-۱۵-۱۳-۳۴-۲۴-۶۹۵_org.videolan.vlc.jpg…]()

thanks

**Comment by Marco-9456** [comment] 2023-04-15 12:38
> 

بتتكلم عربي؟

**Comment by amir385276** [comment] 2023-04-15 12:39
pics this here
ghost
https://i.is.cc/rviqHLc.png

green cubes
https://i.is.cc/rvosAWj.png

**Comment by Marco-9456** [comment] 2023-04-15 12:39
بتتكلم عربي؟
اذا بتتكلم، فهمني وين مشكلتك.

**Comment by amir385276** [comment] 2023-04-15 12:40
> > 
> 
> بتتكلم عربي؟

Not i Can't
Just english and persian
يتكلم فارسي.

**Comment by amir385276** [comment] 2023-04-15 12:51
Ok
main video in the youtube is great and without any  green shadows 
i do paste the link in "seal" then downloading 
after the downloading all fragments of video when  thee seal  wants to paste all fragments to main video
i think maybe mutagen have a issue e with some videos that can't merge all fragmentations  into the main video

i try sometimes but in  the  all of  process some parts have a green cubes like cheese
I remember 3 years go the youtube-dl have this issue and fixed
thanks  Marco-9456

**Comment by amir385276** [comment] 2023-04-15 12:52
I can't explain correctly but i wanna to create a short video for you

thanks a lot

**Comment by JunkFood02** [comment] 2023-04-22 16:47
Duplicate of #500

**Closed** 2023-06-23 17:58 UTC
Labels: enhancement
