### ISSUE TITLE
Playlist download error 

### ISSUE THREAD

**Issue by nascentphilosopher** [JunkFood02/Seal#1569] opened 2024-07-08 20:24 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Download error happening 

### To Reproduce

App version: 2.0.0-alpha.1 (20002)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.07.232743

URL: https://piped.video/playlist?list=PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI
[debug] Command-line config: ['--no-mtime', '-v', '--download-archive', '/data/user/0/com.junkfood.seal.preview/files/archive.txt', '--playlist-items', '35', '--downloader', 'libaria2c.so', '--add-metadata', '--no-embed-info-json', '-S', 'vcodec:vp9.2,acodec:aac', '--sub-langs', 'en.*,.*-orig', '--embed-subs', '--remux-video', 'mkv', '--merge-output-format', 'mkv', '--embed-chapters', '--sponsorblock-remove', 'default', '--write-thumbnail', '--convert-thumbnails', 'png', '-P', '/storage/emulated/0/Download/Seal/tmp/PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--external-downloader-args', 'aria2c:--summary-interval=1', '--external-downloader-args', 'aria2c:--ca-certificate=/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/etc/tls/cert.pem', '--ffmpeg-location', '/data/app/~~BZHiUG0qfUtviJ5VKJuwUQ==/com.junkfood.seal.preview-6ZsQHag6VfmPImq0qvrUfg==/lib/arm64/libffmpeg.so', 'https://piped.video/playlist?list=PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.07.07.232743 from yt-dlp/yt-dlp-nightly-builds [39bc699d2] (zip)
[debug] Python 3.11.8 (CPython aarch64 64bit) - Linux-4.19.191-g8d7f445cecef-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: mutagen-1.47.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Loading archive file '/data/user/0/com.junkfood.seal.preview/files/archive.txt'
[debug] [youtube] Decrypted nsig 5jCaRjgmiw1AWT3r6s- => AUuKmIzOgGOTAw
[debug] [youtube] Decrypted nsig SuaKQ0y5DL4n1eTzDpA => _SkC2xM98u4Azg
[debug] Sort order given by user: vcodec:vp9.2, acodec:aac
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:vp9.2(10), acodec:aac(10), quality, res, fps, hdr:12(7), source, channels, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/69c1?service=YouTube&categories=%5B%22outro%22%2C+%22music_offtopic%22%2C+%22preview%22%2C+%22intro%22%2C+%22selfpromo%22%2C+%22sponsor%22%2C+%22interaction%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking aria2c downloader on "https://www.youtube.com/api/timedtext?v=sAZNrwKnPww&ei=_kmMZoyhB_nWjuMPkNSawAU&caps=asr&opi=112496729&exp=xbt&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1720495214&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cexp%2Cxoaf&signature=9305FE8CE24865EF4FF145DA000554CDBFE914F6.B2DB6E73A3F85A325BE6C7B4F413C704752533E2&key=yt8&lang=en&name=NPTEL+Official&fmt=vtt"
ERROR: Unable to download video subtitles for 'en-LUU0EuDKgKo': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4350, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3199, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 50, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 294, in _call_downloader
    return super()._call_downloader(tmpfilename, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 145, in _call_downloader
    cmd = [encodeArgument(a) for a in self._make_cmd(tmpfilename, info_dict)]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 306, in _make_cmd
    cmd += [f'--load-cookies={self._write_cookies()}']
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 135, in _write_cookies
    tmp_cookies = tempfile.NamedTemporaryFile(suffix='.cookies', delete=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 562, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 127, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 316, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 309, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 224, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3012, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3267, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4358, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'en-LUU0EuDKgKo': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Error reports

App version: 2.0.0-alpha.1 (20002)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.07.232743

URL: https://piped.video/playlist?list=PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI
[debug] Command-line config: ['--no-mtime', '-v', '--download-archive', '/data/user/0/com.junkfood.seal.preview/files/archive.txt', '--playlist-items', '35', '--downloader', 'libaria2c.so', '--add-metadata', '--no-embed-info-json', '-S', 'vcodec:vp9.2,acodec:aac', '--sub-langs', 'en.*,.*-orig', '--embed-subs', '--remux-video', 'mkv', '--merge-output-format', 'mkv', '--embed-chapters', '--sponsorblock-remove', 'default', '--write-thumbnail', '--convert-thumbnails', 'png', '-P', '/storage/emulated/0/Download/Seal/tmp/PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--external-downloader-args', 'aria2c:--summary-interval=1', '--external-downloader-args', 'aria2c:--ca-certificate=/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/etc/tls/cert.pem', '--ffmpeg-location', '/data/app/~~BZHiUG0qfUtviJ5VKJuwUQ==/com.junkfood.seal.preview-6ZsQHag6VfmPImq0qvrUfg==/lib/arm64/libffmpeg.so', 'https://piped.video/playlist?list=PLq-Gm0yRYwThKeMSP_ii5klqDYvta4HQI']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.07.07.232743 from yt-dlp/yt-dlp-nightly-builds [39bc699d2] (zip)
[debug] Python 3.11.8 (CPython aarch64 64bit) - Linux-4.19.191-g8d7f445cecef-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: mutagen-1.47.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Loading archive file '/data/user/0/com.junkfood.seal.preview/files/archive.txt'
[debug] [youtube] Decrypted nsig 5jCaRjgmiw1AWT3r6s- => AUuKmIzOgGOTAw
[debug] [youtube] Decrypted nsig SuaKQ0y5DL4n1eTzDpA => _SkC2xM98u4Azg
[debug] Sort order given by user: vcodec:vp9.2, acodec:aac
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:vp9.2(10), acodec:aac(10), quality, res, fps, hdr:12(7), source, channels, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/69c1?service=YouTube&categories=%5B%22outro%22%2C+%22music_offtopic%22%2C+%22preview%22%2C+%22intro%22%2C+%22selfpromo%22%2C+%22sponsor%22%2C+%22interaction%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking aria2c downloader on "https://www.youtube.com/api/timedtext?v=sAZNrwKnPww&ei=_kmMZoyhB_nWjuMPkNSawAU&caps=asr&opi=112496729&exp=xbt&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1720495214&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cexp%2Cxoaf&signature=9305FE8CE24865EF4FF145DA000554CDBFE914F6.B2DB6E73A3F85A325BE6C7B4F413C704752533E2&key=yt8&lang=en&name=NPTEL+Official&fmt=vtt"
ERROR: Unable to download video subtitles for 'en-LUU0EuDKgKo': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4350, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3199, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 50, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 294, in _call_downloader
    return super()._call_downloader(tmpfilename, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 145, in _call_downloader
    cmd = [encodeArgument(a) for a in self._make_cmd(tmpfilename, info_dict)]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 306, in _make_cmd
    cmd += [f'--load-cookies={self._write_cookies()}']
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 135, in _write_cookies
    tmp_cookies = tempfile.NamedTemporaryFile(suffix='.cookies', delete=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 562, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 127, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 316, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 309, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/packages/python/usr/lib/python3.11/tempfile.py", line 224, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3012, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3267, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.junkfood.seal.preview/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4358, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'en-LUU0EuDKgKo': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

**Comment by JunkFood02** [comment] 2024-08-14 13:34
Duplicate of #1161

**Closed by JunkFood02** 2024-08-14 13:34 UTC
Labels: bug, new issue
