### ISSUE TITLE
[Feature Request] using popup window when sharing from other apps

### ISSUE THREAD

**Issue by lewdpatriot** [JunkFood02/Seal#563] opened 2023-02-03 05:35 UTC
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When sharing through android share it opens the full seal app making it to go back and forth whenever trying to download a video. 

### Describe the solution you'd like

Please make it a popup window when sharing the video link for downloading ( instead of opening the full app). Newpipe uses this kind of popups. 

### Additional context

![Screenshot_2023-02-03-10-52-09-07_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/63286528/216520707-a0892fb6-5ba7-4cd8-b896-6c4d50a6e4ba.jpg)

**Comment by JunkFood02** [comment] 2023-02-03 05:36
Duplicate of #152

**Closed by JunkFood02** 2023-02-03 05:36 UTC
Labels: enhancement

**Comment by lewdpatriot** [comment] 2023-02-03 05:45
So is it being worked on or is it not the focus right now? ( also thank you for developing the app).

**Comment by Marco-9456** [comment] 2023-02-03 05:46
> So is it being worked on or is it not the focus right now? ( also thank you for developing the app).

No, it's implemented but you're using an old build of the app

**Comment by lewdpatriot** [comment] 2023-02-03 05:50
> > So is it being worked on or is it not the focus right now? ( also thank you for developing the app).
> 
> No, it's implemented but you're just using an old build of the app

Oh, ok. Thank you
