### ISSUE TITLE
problem downloading Crunchyroll

### ISSUE THREAD

**Issue by kowvac** [JunkFood02/Seal#916] opened 2023-07-02 14:59 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

yt-dlp updated but the error remains. Is this error browser related or is it in yt-dlp? I use Vivaldi

### Error reports

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.30.182724

URL: https://www.crunchyroll.com/pt-br/watch/G6MG8XG86/chivalry-remains-the-traitorous-zombie-protects-nami
ERROR: [crunchyroll] G6MG8XG86: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_2023-07-02-11-55-34-282_com junkfood seal](https://github.com/JunkFood02/Seal/assets/102343994/2b0a7a41-6120-4269-842c-57f9ee005596)

### Device info

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.30.182724

### Additional context

Is there any way to fix this, or only in yt-dlp updates?

**Comment by JunkFood02** [comment] 2023-07-03 07:23
Duplicate of #894

**Closed by JunkFood02** 2023-07-03 07:23 UTC
Labels: bug, duplicate, upstream
