### ISSUE TITLE
Could not fetch video info from YouTube

### ISSUE THREAD

**Issue by ksi** [JunkFood02/Seal#1059] opened 2023-09-07 18:40 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I share YouTube video from the official app or Newpipe sometimes I get "Could not fetch video info". If I share the same video right after that a moment later - the download will start. Usually it happens after long period the app (seal) was not being used. It looks like it was unloaded by Android and cannot init something on the first share and full app start.  

### Error reports

The toast "Could not fetch video info". 
App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.09.05.203540

URL: 
instance not initialized

**Comment by ksi** [comment] 2023-09-11 07:58
If I just share to Seal after long inactivity, l get 
`App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.09.09.151504

java.lang.RuntimeException: Unable to resume activity {com.junkfood.seal/com.junkfood.seal.MainActivity}: coil.network.HttpException: lateinit property downloadViewModel has not been initialized
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5074)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5117)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: coil.network.HttpException: lateinit property downloadViewModel has not been initialized
	at com.junkfood.seal.MainActivity.handleShareIntent(Unknown Source:112)
	at com.junkfood.seal.MainActivity.onNewIntent(Unknown Source:5)
	at android.app.Activity.performNewIntent(Activity.java:8438)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1503)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1516)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4058)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5045)
	... 13 more
`

**Comment by fillwithjoy1** [comment] 2023-09-11 09:04
What specific device do you have and try to download (this)[https://www.youtube.com/watch?v=dQw4w9WgXcQ] video link, does it work?

**Comment by ksi** [comment] 2023-09-11 09:17
Yes this link works. Actually any work but somethimes not from the firs share. But I got your point. I use Realme GT Neo 3. And I will add Seal to all battery optimization exclusions to see if it help. Previous version of Seal worked fine without such exclusion.

**Comment by JunkFood02** [comment] 2023-09-11 09:22
Thanks for the report, I'll look into it

**Comment by fillwithjoy1** [comment] 2023-09-11 09:26
> Yes this link works. Actually any work but somethimes not from the firs share. But I got your point. I use Realme GT Neo 3. And I will add Seal to all battery optimization exclusions to see if it help. Previous version of Seal worked fine without such exclusion.

Check this page out and add seal to exclusions. See if it works later
https://dontkillmyapp.com/realme

**Comment by ksi** [comment] 2023-09-12 08:25
Exclusion Seal from all battery optimizations didn't help. Still have the same issue.

**Comment by jabed11** [comment] 2023-09-21 07:27
Twitter video download issue "couldn't fetch video info"

**Comment by ksi** [comment] 2023-10-24 09:23
The issue is still reproducible in 1.11.0-b2

**Comment by JunkFood02** [comment] 2023-10-24 19:59
This issue is a bit complicated, because the error `instance not initialized` and the error `java.lang.RuntimeException: Unable to resume activity` are actually come from different part of the code base. And I believe the issue which persists in 1.11.0-beta.2 is the former

**Comment by 2legit2git** [comment] 2023-11-17 05:11
I'm not sure if this help, but I've attached a screenshot and a screen capture video of the error occuring. 

I'm on the latest build. 

It doesn't always happen, but when I attempt a download, the toast indicating the error displays. If I attempt the download again, it will download. 

The `fetch_info_error_msg` error appears in two files:
app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt
app/src/main/java/com/junkfood/seal/Downloader.kt

If a unique error message was thrown for each error, perhaps it could narrow down which function is throwing the error. 

I hope this helps. If you need any additional information, please let me know. Thanks.

![Screenshot_20231116_233921_Photos](https://github.com/JunkFood02/Seal/assets/5898162/f46a9026-39a7-4fad-8048-7e81c6760ab6)

https://github.com/JunkFood02/Seal/assets/5898162/18516189-bf5f-485a-9a68-6edde33a0b31

**Comment by vbhv55** [comment] 2024-06-30 06:58
App version: 1.12.1 (11210)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.06.29.232730

URL: https://www.instagram.com/reel/C7OOZYoqhl7/?igsh=dXdybzB1cjVhYXoz
WARNING: [Instagram] C7OOZYoqhl7: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C7OOZYoqhl7: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

**Comment by Zimso** [comment] 2024-08-15 13:25
I had the same issue and found the cause to be that I had transferred the seal APK from my old phone. Reinstalling did not fix it but if you clear the app data I found that fixes the issue.

**Closed** 2024-10-10 19:08 UTC
Labels: bug, pending
