### ISSUE TITLE
[Feature Request] Add feature to config default filename template

### ISSUE THREAD

**Issue by nhantrn** [JunkFood02/Seal#853] opened 2023-06-02 02:55 UTC
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Currently, there's no way to config filename for the default template unless making a custom template in the default downloader setting. But that would mean you would also have to preconfiguring video+audio qualities etc.

### Describe the solution you'd like

Add a textbox section in Settings > Format page to allow configuring the filename for the default template. Yt-dlp already allows custom filename. For example the textbox would contain something like this: 

> %(channel)s - %(title)s -- %(upload_date)s %(id)s.%(ext)s

It would be then included in the default template command.

Update: Apparently, you can config the subfolders name without `/` and it'll be append into the filename. But the final filename will still get the default filename templat %(id).%(ext)s appended. So that still doesn't solves the request. Perhaps this could be consolidated and allow it to override the default filename template. Or make them separate sections. My feature request still stands.

**Comment by Marco-9456** [comment] 2023-06-02 09:09
Go to settings-->Download Directory-->Custom subdirectory:
There you have the option to change the output.

**Comment by JunkFood02** [comment] 2023-06-02 09:30
duplicate of #675

**Closed by JunkFood02** 2023-06-02 09:30 UTC
Labels: enhancement
