### ISSUE TITLE
[Feature Request]flac audio format

### ISSUE THREAD

**Issue by pizzapielordtemptest** [JunkFood02/Seal#856] opened 2023-06-02 16:59 UTC
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Seal is missing a audio format that doesn't have compression like flac.

### Describe the solution you'd like

Could the flac audio format be added to seal?

### Additional context

Sorry for the bad english.

**Comment by Marco-9456** [comment] 2023-06-02 18:08
We can't add an audio format that youtube/music doesn't support, Seal downloads audio/video file in original format(untouched) from the source

**Comment by JunkFood02** [comment] 2023-06-02 18:22
duplicate of #228

**Closed by JunkFood02** 2023-06-02 18:22 UTC
Labels: enhancement
