### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KazKaz90** [JunkFood02/Seal#108] opened 2022-08-10 15:29 UTC
Is it possible to have the specify playlist and custom commands work together?

**Comment by JunkFood02** [comment] 2022-08-10 15:41
Which command option do you want to use? Btw, all of the download functions can be done with custom commands, so you can download a playlist with a specific command without any GUI options

**Comment by KazKaz90** [comment] 2022-08-10 15:57
> Which command option do you want to use?

This is my custom command
`-o "%(extractor)s/%(uploader)s/%(title)s - %(id)s.%(ext)s"`

>Btw, all of the download functions can be done with custom commands, so you can download a playlist with a specific command without any GUI options

Yes, but I believe it would be preferable to have an option to make the GUI option always appear even when using custom commands, as it is inefficient to constantly change the custom commands given that this app is, as stated, a GUI for yt-dlp.

**Comment by JunkFood02** [comment] 2022-08-10 16:29
> This is my custom command
-o "%(extractor)s/%(uploader)s/%(title)s - %(id)s.%(ext)s"

If you're using the latest version v1.0.2, you can specify a suffix for the output `-o` in the "Download directory" settings 

> Yes, but I believe it would be preferable to have an option to make the GUI option always appear even when using custom commands

The GUI setting doesn't simply add several lines into the commands. In the normal download mode using GUI options, Seal scans the files into the system media library, extracts and stores the info from videos, so you can manage them on the Downloads page. 

>, as it is inefficient to constantly change the custom commands given that this app is, as stated, a GUI for yt-dlp.

In the next releases, we plan to implement the feature of command templates management in the app.

**Comment by KazKaz90** [comment] 2022-08-10 17:02
> If you're using the latest version v1.0.2, you can specify a prefix for the output `-o` in the "Download directory" settings

This solved my problem, but it appears that playlist selection is broken, for example, if I set the start value to 1 and the end value to 5, it downloaded the first video but the progress bar remained at 1/5 and continued downloading everything instead of the one I set as the end value.

**Comment by JunkFood02** [comment] 2022-08-10 18:01
Could you please provide the link to the playlist for testing?

**Comment by KazKaz90** [comment] 2022-08-10 20:46
> Could you please provide the link to the playlist for testing?

Every Redgifs user, it's strange because it works on 1.0.0, which I had before updating to 1.0.2.

**Comment by JunkFood02** [comment] 2022-08-10 21:00
Reproduced, it's a site-specific bug with v1.0.2 and will get fixed in the next version.

**Comment by KazKaz90** [comment] 2022-08-10 21:50
> Reproduced, it's a site-specific bug with v1.0.2 and will get fixed in the next version.

Thanks!

> *Use v1.0.0 for a temporary workaround

Yeah and using the custom commands --playlist-start and end

Also, as a suggestion for the custom subdirectory, it should be possible to override the file's default naming because if i put `%(uploader)s/%(title)s(%(id)s).%(ext)s` on the path template, the output filename is really messy for example like this _"Bikini Nostalgia Swimsuit Tanned (kindheartedreasonableauk).mp4Bikini Nostalgia Swimsuit Tanned-1134759176.mp4"_

The first is the path template's output, and the second is the app's default output.

**Comment by JunkFood02** [comment] 2022-08-10 22:03
The custom subdirectory is only used for directory tho. The filename template currently is `%(title).60s.%(ext)s` and cannot be modified due to some filename control and operations. If you really need the `id` field to appear in filenames, using `%(uploader)s/%(id)s` is just fine

**Comment by KazKaz90** [comment] 2022-08-10 22:16
> The custom subdirectory is only used for directory tho. The filename template currently is `%(title).60s.%(ext)s` and cannot be modified due to some filename control and operations.

That makes sense; if only custom commands and playlist selection could work together like custom subdirectory, it would be ideal because the GUI playlist selection knows how many videos the user or playlist has.

> If you really need the `id` field to appear in filenames, using `%(uploader)s/%(id)s` is just fine

Yeah but the `id` will always be at the start of the filename

**Comment by JunkFood02** [comment] 2022-08-10 22:42
> The GUI setting doesn't simply add several lines into the commands. In the normal download mode using GUI options, Seal scans the files into the system media library, extracts and stores the info from videos, so you can manage them on the Downloads page.

Currently, these features heavily depend on the filename controlling and limited options, modifying file names or introducing new features may cause errors in these features(like the one you experienced in v1.0.2). Thus, mixing custom commands with the GUI options could bring tons of corner cases and bugs, which I really don't want to deal with. 😌

**Comment by KazKaz90** [comment] 2022-08-11 01:24
That's unfortunate, but thanks anyway.

**Comment by JunkFood02** [comment] 2022-08-11 05:12
Fixed in v1.0.3

**Closed by JunkFood02** 2022-08-11 05:12 UTC
