### ISSUE TITLE
[Feature Request] Music formats.

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#573] opened 2023-02-04 21:33 UTC
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Add audio quality section to advanced settings section during fast download

### Describe the solution you'd like

Sound qualities.
1.Mp3 70K
2.MP3 128K
3.M4A 128K
4.MP3 160K
5.MP3 320K

### Video link

All

**Comment by JunkFood02** [comment] 2023-02-05 10:33
Duplicate of #564

**Closed by JunkFood02** 2023-02-05 10:33 UTC
Labels: enhancement
